title: Xinrui Zhou's Homepage
page-top-title: Xinrui Zhou's Homepage
top-section-bg-text: Lanxun Inc.
home-subtitle: Xinrui Zhou 
copyright-text: '&copy; Xinrui Zhou 2024. All Rights Reserved. Template by Xinrui Zhou From <a href="https://github.com/xinrui-z/xinrui-z.github.io">This Repo</a>.'
